// This file is automatically generated. Do not modify it manually.
// To regenerate this file, RUN "firebase:bootstrap"
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}'
);
